import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout der Anwendung.
 * Setzt die Schriftarten (Geist Sans und Geist Mono) und die Sprache des HTML-Dokuments.
 *
 * @param {object} props - Die Props, die an das RootLayout übergeben werden.
 * @param {React.ReactNode} props.children - Die untergeordneten React-Komponenten.
 * @param {object} props.params - Die URL-Parameter, z.B. für die Sprache.
 * @param {string} [props.params.lang] - Der Sprachcode (z.B. "de" oder "en").
 *
 * @returns {JSX.Element} Das HTML-Layout mit Sprachattribut und eingebundenen Schriftarten.
 */
export default async function RootLayout({ children, params }) {
  const param = await params;
  const lang = param.lang || "de";

  return (
    <html className="main text-base-content bg-base-200" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
