import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderWithSidebar from "@/components/structure/HeaderWithSidebar";
import Footer from "@/components/structure//footer";
import { getDictionary } from "@/lib/getDictionary";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const lang = params?.lang || "de";
  await getDictionary(lang); // Nur notwendig, wenn dict gebraucht wird

  return (
    <html className="main text-base-content" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderWithSidebar lang={lang}>{children}</HeaderWithSidebar>
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
