import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import HeaderWithSidebar from "@/components/structure/HeaderWithSidebar";
import Footer from "@/components/structure//footer";
import { getDictionary } from "@/lib/getDictionary";
import { getUserAction } from "@/app/actions/userActions";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Layout-Komponente der Anwendung
 *
 * Dieses Layout definiert die grundlegende Struktur der App-Seiten.
 * Es umfasst Header mit Sidebar, den Content-Bereich (children) und den Footer.
 *
 * - `children`: Der Hauptinhalt der Seite, der innerhalb des Layouts gerendert wird.
 * - `params`: URL-Parameter, über die unter anderem die Sprache (`lang`) bestimmt wird.
 * - Die Sprachdaten werden serverseitig über `getDictionary` geladen.
 * - Die Benutzerdaten werden über `getUserAction` abgerufen, um den Login-Status zu bestimmen.
 * - Der Login-Status wird als Boolean `loggedIn` an den Header weitergereicht.
 *
 * @param {Object} props
 * @param {React.ReactNode} props.children - Inhalt der jeweiligen Seite
 * @param {Object} props.params - URL-Parameter (z.B. mit `lang`)
 *
 * @returns {JSX.Element} Gerendertes Layout mit Header, Content und Footer
 */
export default async function Layout({ children, params }) {
  const param = await params;
  const lang = param.lang || "de";
  const dict = await getDictionary(lang);
  const user = await getUserAction();
  let loggedIn = false;
  if (user?.id != null || user?.id != undefined) {
    loggedIn = true;
  }

  return (
    <div className="main text-base-content">
      <HeaderWithSidebar lang={lang} dict={dict} user={loggedIn}>
        {children}
      </HeaderWithSidebar>
      <div className="min-h-screen">{children}</div>
      <Footer dict={dict.footer} project={dict.generall} />
    </div>
  );
}
